# Dockerfile_agent

FROM python:3.10

WORKDIR /app

# Copy only requirements, to cache them in docker layer
COPY pyproject.toml .
COPY poetry.lock .

# Project initialization:
RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi --no-root

COPY agent.py .

ARG agent_id
ARG port
ENTRYPOINT ["python", "agent.py"]