# Dockerfile_env
FROM python:3.10

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .

ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --only main --no-root

COPY env.py .

ENTRYPOINT ["python", "env.py"]