# Dockerfile_agent
FROM python:3.10

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .

ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev --no-interaction --no-ansi

COPY agent.py .

ENTRYPOINT ["python", "agent.py"]