version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - agent-network
  agent_0:
    build:
      context: .
      dockerfile: dockerfile.agent
    command: ['agent_0', '5000']
    networks:
      - agent-network
  agent_1:
    build:
      context: .
      dockerfile: dockerfile.agent
    command: ['agent_1', '5000']
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
